name: program_valve
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  stacked: ^3.2.7
  path_provider: ^2.0.15
  sqflite: ^2.2.8+4
  stacked_services: ^1.0.2
  get_it: ^7.6.0
  dio: ^5.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.4 
  stacked_generator: ^1.3.3
  flutter_native_splash:
  flutter_launcher_icons: ^0.13.1
  pretty_dio_logger: ^1.3.1




flutter:


  uses-material-design: true

  